#ASSIGNMENT=wp1p1
#ASSIGNMENT=wp1
ASSIGNMENT=wp2
#ASSIGNMENT=wp3
#ASSIGNMENT=project
TEAM_MEMBERS_CSV="Mridul Ranjan (111482003, NET ID: mranjan), Rohit Kumar (111471168, NET ID: rokkumar)"
# list space-separated completed components: cooperative preemptive signals swap filesystem network multicore
PROJECT_PARTS=cooperative signals
PROJECT_POINTS=50
