#ASSIGNMENT=wp1p1
#ASSIGNMENT=wp1
#ASSIGNMENT=wp2
ASSIGNMENT=wp3
#ASSIGNMENT=project
TEAM_MEMBERS_CSV="Rohit Kumar (rokkumar - 111471168), Mridul Ranjan (mranjan - 111482003)"
# list space-separated completed components: cooperative preemptive signals swap filesystem network multicore
PROJECT_PARTS=cooperative signals
PROJECT_POINTS=50
